### ISSUE TITLE
The HF space is not functioning

### ISSUE THREAD

**Issue by robmarkcole** [gauthamk02/pytorch-waterbody-segmentation#1]
as title

**Comment by robmarkcole** [comment]
Updated reqs for the app on https://github.com/robmarkcole/pytorch-waterbody-segmentation/blob/main/requirements.txt

**Comment by gauthamk02** [comment]
Hey Rob

Thanks for bringing this to my attention. I just had to upgrade gradio to `gradio==3.50.2` to get the space working. 

You can check out the deployment at https://huggingface.co/spaces/gauthamk/water-body-segmentation

**Comment by robmarkcole** [comment]
All fixed!
